import conf from "../conf/conf";
import { Client, ID, Databases, Storage, Query } from "appwrite";

export class Service{
    client = new Client();
    databases;
    storage; // or bucket

    constructor() {
        this.client
            .setEndpoint(conf.appwriteURL)          // Your API Endpoint
            .setProject(conf.appwriteProjectId);    // Your project ID

        this.databases = new Databases(this.client);
        this.storage = new Storage(this.client);
            
    }

    async createPost({title, slug, content, featuredImage, status, userId})
    {
        try 
        {
            // const result = await databases.createDocument({databaseId: , collectionId: , documentId:, data: {}
            // We need the same paramenter in sequence everytime we create this document.
            return await this.databases.createDocument(
                conf.appwriteDatabaseId,
                conf.appwriteCollectionId,
                slug, // we are using slug as unique id because we want to use that slug in url to access the post and if we use ID.unique() then we won't be able to access the post using slug in url because it will be different from the unique id generated by appwrite. So, we are using slug as unique id for our posts.
                {
                    title,
                    content,
                    featuredImage,
                    status,
                    userId,
                }
            )   
        } 
        catch (error) 
        {
            console.log("Appwrite service :: createPost :: error", error);
        }
    }

    // Here we are passing slug as id.
    async updatePost(slug, {title, content, featuredImage, status})
    {
        try 
        {
            return await this.databases.updateDocument(
                conf.appwriteDatabaseId,
                conf.appwriteCollectionId,
                slug, 
                {
                    title,
                    content,
                    featuredImage,
                    status,
                }
            )
        } 
        catch (error) 
        {
            console.log("Appwrite service :: updatePost :: error", error);
        }
    }

    async deletePost(slug)
    {
        try 
        {
            await this.databases.deleteDocument(
                conf.appwriteDatabaseId,
                conf.appwriteCollectionId,
                slug, 
            )
            return true
            
        } 
        catch (error) 
        {
            console.log("Appwrite service :: deletePost :: error", error);
            return false;
        }
    }

    async getPost(slug)
    {
        try 
        {
            return await this.databases.getDocument(
                conf.appwriteDatabaseId,
                conf.appwriteCollectionId,
                slug, 
            )
        } 
        catch (error) 
        {
            console.log("Appwrite service :: getPost :: error", error);
            return false;
        }
    }

    // If we don't use queries then we will get all the posts. Now we will get only those posts whose status is active.
    async getPosts(queries = [Query.equal("status", "active")])
    {
        try 
        {
            return await this.databases.listDocuments(
                conf.appwriteDatabaseId,
                conf.appwriteCollectionId,
                queries
            )
        } 
        catch (error) 
        {
            console.log("Appwrite service :: getPosts :: error", error);
            return false;
        }
    }

    async uploadFile(file)
    {
        try 
        {
            return await this.storage.createFile(
                conf.appwriteBucketId,
                ID.unique(),
                file
            )    
        } 
        catch (error) 
        {
            console.log("Appwrite service :: uploadFile :: error", error);
            return false;
        }
    }

    // This fileId is the id of the file that we want to delete. We can get the fileId from the response of the uploadFile method. When we upload a file then we get the fileId in the response and we can use that fileId to delete the file.
    async deleteFile(fileId)
    {
        try 
        {
            await this.storage.deleteFile(
                conf.appwriteBucketId,
                fileId
            )    
            return true;
        } 
        catch (error) 
        {
            console.log("Appwrite service :: deleteFile :: error", error);
            return false;
        }
    }

    // async getFilePreview(fileId)
    // {
    //     return this.storage.getFilePreview(
    //         conf.appwriteBucketId,
    //         fileId
    //     )
    // }

    getFilePreview(fileId) {
    return `${conf.appwriteURL}/storage/buckets/${conf.appwriteBucketId}/files/${fileId}/view?project=${conf.appwriteProjectId}`
}
}

const service = new Service()

export default service;